---
title: "Project and Data Organization"
author: "Michael Kistner"
date: "May 16, 2022"
output: html_notebook
---

# Introduction 

Welcome! This notebook is the first in a five part series on data cleaning using the **tidyverse**. The intended audience is a quantitative social science practitioner who has previously used R, but who wants to learn more about data cleaning and is less familiar (or unfamiliar) with the collection of packages known as the **tidyverse**. Packages in the **tidyverse** all share a similar syntax and coding philosophy, and are designed to work together nicely.^[Individual packages we'll encounter include **dplyr**, **readr**, **tidyr**, **ggplot2**, **stringr**, and **lubridate**] 

The substantive focus of this short workshop is introducing a set of tools for data management, cleaning, manipulation, and exploration using R and the **tidyverse**. When thinking about the broader research process for a quantitative empirical project, an extremely simplified model of the process might be:

$$\textrm{Develop Question} \rightarrow \textrm{Collect Data} \rightarrow \textrm{Clean and Manipulate Data} \rightarrow \textrm{Analyze Data} \rightarrow \textrm{Share Findings} $$ 

In a typical graduate program, students might cover steps 1 and 2 in a research design course, learn step 4 in their methods classes, and get practice at step 5 via seminar papers, writing a prospectus, and presenting research in a workshop. It's less typical for students to get formal training in step 3. While there is more material than we'll have time to cover in this workshop alone, we'll introduce a set of powerful tools for commonly encountered situations in computational social science. As we go, I'll share resources that will allow students to dive deeper into these topics. Much of the material I'm presenting is drawn from ["R for Data Science" by Hadley Wickham and Garrett Grolemund](https://r4ds.had.co.nz/index.html). In addition to showing you how to use tools, I'll also share my approach to project organization and management. This is a system developed via trial and error, and has proven incredibly useful to me, but there are alternative ways to organize and manage a project such as this.^[One useful guide that shares some, but not all, features in common with what I'll introduce here, is ["Code and Data for the Social Sciences: A Pracitioner's Guide" by Matthew Gentzkow and Jesse M. Shapiro](https://web.stanford.edu/~gentzkow/research/CodeAndData.xhtml).] 

Before we go any further, let's take a moment to (re-)familiarize ourselves with what's going on when we open up RStudio. RStudio displays four different panes when you're working with code. The top left pane, where you're probably reading this, is known as the *Source* pane. If you're working on a notebook (like this document) or a script, it will appear here. You can also view datasets you're working with in this pane using RStudio's built-in data viewer. The bottom left pane is the *Console*, where you can run lines of code directly, although you can run code from a notebook or script as well. If you want to save code so everything you do is reproducible (which you should be doing 99% of the time), you need to make sure to put it in your script or notebook, as code you run in the console will not be saved. The top right pane shows (among other things) the *Environment*. When you load data or create objects, their names and details will appear in this pane, and the environment pane is useful for keeping track of what you've created, what variable names are, etc.. Finally, the bottom left pane shows the *File* directory. You can load data or open a notebook from here, for example. It's also where help files will appear if you ask R to explain how a function or command works, or plots be displayed if you're not working a notebook. 

Speaking of which, this document is an *R Markdown Notebook*. The two most common types of code documents you'll work with are notebooks and scripts. An R script contains nothing but code and short comments about what the code is doing. It's meant primarily to accomplish one focused coding job (merging datasets, running a series of regressions, etc.) and do little else. In contrast, a notebook contains a combination of text, like what you're reading now, chunks of code that accomplish specific tasks, and plot output. You can add all sorts of formatting to make everything look neat, and you can compile the text, code, and output into a readable document like a PDF or HTML file using R's markdown language. I typically use a series of individual R scripts for data cleaning and management, but conduct analyses in a notebook that make it easy to go back and forth between sections and see previous output as I continue to analyze. 

```{r}
library(tidyverse)
```

